---

- name: Install PHP 7.1
  apt: name={{item}} state=installed
  with_items: 
    - php7.1 
    - libapache2-mod-php7.1 
    - php7.1-common 
    - php7.1-mbstring 
    - php7.1-xmlrpc
    - php7.1-soap
    - php7.1-gd
    - php7.1-xml
    - php7.1-intl
    - php7.1-mysql
    - php7.1-cli
    - php7.1-mcrypt
    - php7.1-zip
    - php7.1-curl
  sudo: yes